version: "2.1"
services:
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongo", "localhost:27017" ]
      interval: 5s
      timeout:  5s
      retries:  3